command:
  - uvicorn
  - app:app
  - --host
  - 0.0.0.0
  - --port
  - "8000"
env:
  - name: DBXSC_AI_DB_HOST
    value: "ep-restless-cake-d2jpldze.database.us-east-1.cloud.databricks.com"
  - name: DBXSC_AI_DB_PORT
    value: "5432"
  - name: DBXSC_AI_DB_NAME
    value: "scenic_crawler"
  - name: DBXSC_AI_DB_SCHEMA
    value: "public"
  - name: DBXSC_AI_LAKEBASE_PROJECT
    value: "scenic-crawler"
  - name: DBXSC_AI_LAKEBASE_BRANCH
    value: "production"
  - name: DBXSC_AI_LAKEBASE_ENDPOINT
    value: "primary"
  - name: DBXSC_AI_DB_USER
    value: "9f451c92-d204-42de-91e3-92bcdabc1dd2"
  - name: DBXSC_AI_DB_PASSWORD
    value: "6KM3AJkX06927_Gpt04c9RUjb9ftiZDY"
  - name: FMAPI_MODEL
    value: "databricks-llama-4-maverick"
  - name: VIDEO_VOLUME
    value: "/Volumes/jsf_demo_catalog/scenic_crawler/uploaded_videos"
  - name: THUMBNAIL_VOLUME
    value: "/Volumes/jsf_demo_catalog/scenic_crawler/thumbnails"
resources:
  - name: serving-endpoint
    serving_endpoint:
      name: databricks-llama-4-maverick
      permission: CAN_QUERY
